### lOGIN 
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
    "akunId": "2309106028",
    "password": "password"
}

### AKUN
## Create Akun
POST http://localhost:8081/api/v1/akun
Content-Type: application/json

{
    "akunId": "2309106028",
    "nama": "Staff1",
    "role": "ADMIN",
    "password": "admin123",
    "email": "damn@gmail.com"
}


## View All Akun
GET http://localhost:8081/api/v1/akun

## Update Akun
PUT http://localhost:8081/api/v1/akun/2309106028
Content-Type: application/json

{
    "nama": "Injil Karepowan",
    "role": "MAHASISWA",
    "password": "admin123",
    "email": "email@gmail.com"
}


