### lOGIN 
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
    "akunId": "2309106028",
    "password": "password"
}

### AKUN
## POST Akun
POST http://localhost:8081/api/v1/akun
Content-Type: application/json

{
    "akunId": "2309106028",
    "nama": "Staff1",
    "role": "ADMIN",
    "password": "admin123",
    "email": "damn@gmail.com"
}


## GET Akun
